environment:

  matrix:

    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"

    - PYTHON: "C:\\Python36_64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"

    - PYTHON: "C:\\Python36_64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit)
  - powershell .\\continuous-integration\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Don't install from requirements-pip.txt, python-coveralls has broken dependencies on windows it seems.
  - pip install -r requirements.txt
  - python setup.py install
  - pip install PyQt5
  - pip install pandas
  - pip install numpy

build: false

test_script:
  # Nosetests take care of unit tests
  # Behave runs the example scripts and tries to verify if it produces the right output
  - nosetests
  #- behave --tags ~@skip # Everything without the tag @skip

on_success:
  # Could run coveralls here but will leave that to travis tests
  - echo Build succesful!
  #- coverage report
# coveralls
